name: Deploy to DockerHub

on:
  workflow_run:
    workflows: ["Run Tests"]  # This is the name of the first workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t jovanovski35/my-app:latest .
          docker push jovanovski35/my-app:latest
