name: Test Workflow

on:
  push:
    branches:
      - main  # Trigger action on push to the main branch
  pull_request:
    branches:
      - main  # Trigger action on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Check out repository
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install dependencies if you have a requirements.txt file

      - name: Run tests
        run: |
          pytest  # Run tests with pytest (you can replace this with your test command)
          
      - name: Verify the 'tests' directory exists
        run: |
          if [ ! -d "tests" ]; then
            echo "Error: The 'tests' directory does not exist.";
            exit 1;
          fi
