name: Deploy to DockerHub

on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # This refers to the Docker Hub username secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # This refers to the Docker Hub Personal Access Token

      - name: Build and push Docker image
        run: |
          docker build -t jovanovski35/my-app:latest .
          docker push jovanovski35/my-app:latest
